export const currentPluginVersion = '2.2.8';

export const changelog = {
'en': 
`
### 2.2.8 updates
🐛 **Bug Fixed:**
- Widget view may appear at an unexpected location when the plugin is re-enabled. 

⚡ **Enhancements:**
- Fixed ES-Lint issues as per Obsidian regulation. 

### 2.2.7 updates
✨ **New Features**:
- File colors under the same tag are easier to distinguish by controling the range slider.

🐛 **Bug Fixed:**
- Note properties with hyphens \`modified-date\` is not recognized by the recorder. 
- Field Alias not recognize data fields from other recorders.

🎨 **UI Optimization**:
- Clarified widget settings for easier understanding
- Files under one tag will be easier to distinguish

### 2.2.6 updates
🐛 **Bug Fixed:**
- AI diff request was sent even when there were no edits to the note.
- Timed-out or failed AI diff requests left a stale loading icon permanently in periodic notes.

🎨 **UI Optimization:**
- Improved font size adaptation to the width of the widget view.

### 2.2.5 updates
✨ **New Features:**
- Auto update link alias to the latest file name after the note is renamed.

🐛 **Bug Fixed:**
- Modified data may be recorded to the wrong date after syncking from the other device.
- Widget not update when detected crossday.
- Links in table of dailynote may be broken by Obsidian. 
- Hover style issue on recorder switcher and field switcher in widget.

⚡ **Enhancements:**
- If links are broken due to Obsidian or any reasons, the plugin will auto fix the broken links (only effective for links generated by this plugin in periodic notes).

### 2.2.4 updates
🎨 **UI Optimization:**
- CSS standardization according to Obsidian specifications.

### 2.2.3 updates
✨ **New Features:**
- AI Diff Summary could now using line-breaks by default. 

⚡ **Enhancements:**
- Removed unnecessary \`!important\` declarations in CSS by increasing selector specificity.
- Fixed duplicate CSS selector in widget settings.
- Replaced deprecated \`builtin-modules\` package with Node.js native \`node:module\`.
- Optimized tag retrieval: replaced vault file enumeration with \`metadataCache.getTags()\` for O(1) performance.
`,
'zh-CN': 
`
### 2.2.8 更新说明
🐛 **Bug 修复：**
- 修复了插件重新启用时，Widget 视图可能出现在意外位置的问题。

⚡ **功能增强：**
- 根据 Obsidian 规范修复了 ES-Lint 相关问题。

### 2.2.7 更新说明
✨ **新功能：**
- 新增色相范围滑块，可调整同一标签下各文件颜色的区分程度。

🐛 **问题修复：**
- 含连字符的笔记属性（如 \`modified-date\`）无法被记录器识别。
- 属性别名无法识别来自其他记录器的数据字段。

🎨 **界面优化：**
- 优化侧栏组件的颜色设置分区说明，使其含义更易理解。

### 2.2.6 更新说明
🐛 **问题修复：**
- 修复即使笔记没有任何编辑时 AI diff 请求仍会发送的问题。
- 修复超时或失败的 AI diff 请求会在周期笔记中留下永久残留加载图标的问题。

🎨 **界面优化：**
- 改进字体大小对组件视图宽度的自适应。

### 2.2.5 更新说明
✨ **新功能：**
- 笔记重命名后自动更新链接别名为最新文件名。

🐛 **问题修复：**
- 修复从其他设备同步后，修改的数据可能被记录到错误日期的问题。
- 修复检测到跨日时组件未更新的问题。
- 修复 Obsidian 自动重命名导致日记表格中的链接损坏的问题。
- 修复鼠标悬停在组件的记录器切换器和字段切换器上时的样式问题。

⚡ **功能强化：**
- 如果链接因 Obsidian 或其他原因损坏，插件将自动修复损坏的链接（仅对周期笔记中由此插件生成的链接有效）。

### 2.2.4 updates
🎨 **UI Optimization:**
- 根据 Obsidian 要求，标准化了 css 的使用。

### 2.2.3 更新说明
✨ **新功能：**
- AI 差异总结现在默认支持换行。

⚡ **功能强化：**
- 通过提高选择器特异性移除 CSS 中不必要的 \`!important\` 声明。
- 修复小部件设置中重复的 CSS 选择器。
- 将已弃用的 \`builtin-modules\` 包替换为 Node.js 内置 \`node:module\`。
- 优化标签获取：使用 \`metadataCache.getTags()\` 替代遍历仓库文件，性能提升至 O(1)。
`
};