export const currentPluginVersion = '2.3.0';

export const changelog = {
'en': 
`
### 2.3.0 updates
🔥 **Major Updates:**
- Rebuilt recorder settings UI: new Property Editor, folder suggestions, and improved interaction logic for more convenient configuration experience.
- **New recorder type: Modified Note Recorder** — directly record accumulated historic edit stats into each modified note itself, ideal for tracking per-note writing progress over time. Supports metadata, bullet list, and scope folder filtering.

✨ **New Features:**
- New Property Editor in recorder settings for structured syntax editing.
- Folder auto-suggestions when configuring periodic note folders.

⚡ **Enhancements:**
- Optimized default settings for better out-of-box experience.
- Improved i18n and tooltips for newly added features.

🐛 **Fixes:**
- Fixed document word count being incorrect due to tracker not updating original words.

### 2.2.9 updates
✨ **New Features:**
- Context Management: AI can now understand changes better by:
    - Document summary: AI can generate a document summary when first indexing a note, providing better understanding of the overall document structure.
    - Document Headings: Heading tree structure can be included with AI requests for better document organization awareness.
    - File chunking: including surrounding context (sentences, paragraphs, or heading sections) around modified areas.

🎨 **UI Optimization**:
- Reorganized AI settings page: added dedicated "Context Management" section and "Advanced" section for clearer configuration.

### 2.2.8 updates
🐛 **Bug Fixed:**
- Widget view may appear at an unexpected location when the plugin is re-enabled. 

⚡ **Enhancements:**
- Fixed ES-Lint issues as per Obsidian regulation. 

### 2.2.7 updates
✨ **New Features**:
- File colors under the same tag are easier to distinguish by controling the range slider.

🐛 **Bug Fixed:**
- Note properties with hyphens \`modified-date\` is not recognized by the recorder. 
- Field Alias not recognize data fields from other recorders.

🎨 **UI Optimization**:
- Clarified widget settings for easier understanding
- Files under one tag will be easier to distinguish

### 2.2.6 updates
🐛 **Bug Fixed:**
- AI diff request was sent even when there were no edits to the note.
- Timed-out or failed AI diff requests left a stale loading icon permanently in periodic notes.

🎨 **UI Optimization:**
- Improved font size adaptation to the width of the widget view.

### 2.2.5 updates
✨ **New Features:**
- Auto update link alias to the latest file name after the note is renamed.

🐛 **Bug Fixed:**
- Modified data may be recorded to the wrong date after syncking from the other device.
- Widget not update when detected crossday.
- Links in table of dailynote may be broken by Obsidian. 
- Hover style issue on recorder switcher and field switcher in widget.

⚡ **Enhancements:**
- If links are broken due to Obsidian or any reasons, the plugin will auto fix the broken links (only effective for links generated by this plugin in periodic notes).

### 2.2.4 updates
🎨 **UI Optimization:**
- CSS standardization according to Obsidian specifications.

### 2.2.3 updates
✨ **New Features:**
- AI Diff Summary could now using line-breaks by default. 

⚡ **Enhancements:**
- Removed unnecessary \`!important\` declarations in CSS by increasing selector specificity.
- Fixed duplicate CSS selector in widget settings.
- Replaced deprecated \`builtin-modules\` package with Node.js native \`node:module\`.
- Optimized tag retrieval: replaced vault file enumeration with \`metadataCache.getTags()\` for O(1) performance.
`,
'zh-CN': 
`
### 2.3.0 更新说明
🔥 **重大更新：**
- 重构记录器设置 UI：新增属性编辑器、文件夹路径建议，全面优化交互逻辑，配置体验更便捷。
- **新增记录器类型：修改笔记记录器（Modified Note Recorder）** — 直接将累积的历史编辑统计写入每个被修改的笔记自身，适合追踪单篇笔记的写作进度。支持 metadata、bullet list 以及作用域文件夹过滤。

✨ **新功能：**
- 新增结构化语法属性编辑器，支持可视化编辑记录语法。
- 周期笔记文件夹支持路径自动建议。

⚡ **功能增强：**
- 优化默认设置，开箱体验更佳。
- 修复新功能的国际化文案和工具提示问题。

🐛 **问题修复：**
- 修复文档字数因 tracker 未更新原文而统计错误的问题。

### 2.2.9 更新说明
✨ **新功能：**
- 上下文管理：AI 差异分析现在可以包含修改位置周围的上下文（按句子、段落或标题切片），让 AI 更准确地理解文档变更。
- 新增文档摘要生成功能：首次建立快照时，AI 可自动生成文档整体摘要，辅助后续差异分析。
- 可随 AI 请求发送文档的标题树结构，帮助 AI 理解文档的组织架构。

⚡ **功能增强：**
- 重新组织 AI 设置页面：新增「上下文管理」分区和「高级」分区，配置更清晰。
- 精简了 Widget 颜色设置的描述文字，移除了冗余选项。

🐛 **问题修复：**
- 属性别名现在能正确从 Widget 获取字段选项，而非静态列表。

### 2.2.8 更新说明
🐛 **Bug 修复：**
- 修复了插件重新启用时，Widget 视图可能出现在意外位置的问题。

⚡ **功能增强：**
- 根据 Obsidian 规范修复了 ES-Lint 相关问题。

### 2.2.7 更新说明
✨ **新功能：**
- 新增色相范围滑块，可调整同一标签下各文件颜色的区分程度。

🐛 **问题修复：**
- 含连字符的笔记属性（如 \`modified-date\`）无法被记录器识别。
- 属性别名无法识别来自其他记录器的数据字段。

🎨 **界面优化：**
- 优化侧栏组件的颜色设置分区说明，使其含义更易理解。

### 2.2.6 更新说明
🐛 **问题修复：**
- 修复即使笔记没有任何编辑时 AI diff 请求仍会发送的问题。
- 修复超时或失败的 AI diff 请求会在周期笔记中留下永久残留加载图标的问题。

🎨 **界面优化：**
- 改进字体大小对组件视图宽度的自适应。

### 2.2.5 更新说明
✨ **新功能：**
- 笔记重命名后自动更新链接别名为最新文件名。

🐛 **问题修复：**
- 修复从其他设备同步后，修改的数据可能被记录到错误日期的问题。
- 修复检测到跨日时组件未更新的问题。
- 修复 Obsidian 自动重命名导致日记表格中的链接损坏的问题。
- 修复鼠标悬停在组件的记录器切换器和字段切换器上时的样式问题。

⚡ **功能强化：**
- 如果链接因 Obsidian 或其他原因损坏，插件将自动修复损坏的链接（仅对周期笔记中由此插件生成的链接有效）。

### 2.2.4 updates
🎨 **UI Optimization:**
- 根据 Obsidian 要求，标准化了 css 的使用。

### 2.2.3 更新说明
✨ **新功能：**
- AI 差异总结现在默认支持换行。

⚡ **功能强化：**
- 通过提高选择器特异性移除 CSS 中不必要的 \`!important\` 声明。
- 修复小部件设置中重复的 CSS 选择器。
- 将已弃用的 \`builtin-modules\` 包替换为 Node.js 内置 \`node:module\`。
- 优化标签获取：使用 \`metadataCache.getTags()\` 替代遍历仓库文件，性能提升至 O(1)。
`
};